# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-05 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PicInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('p_name', models.CharField(max_length=50)),
                ('p_add_date', models.DateTimeField()),
                ('p_last_view_date', models.DateTimeField()),
                ('p_num', models.CharField(max_length=4)),
                ('p_like_number', models.IntegerField()),
                ('p_collection', models.BooleanField()),
                ('p_tag', models.CharField(max_length=200)),
                ('p_color_tag', models.CharField(max_length=100)),
                ('p_first_link', models.CharField(max_length=100)),
                ('p_links', models.CharField(max_length=2000)),
                ('p_look_num', models.IntegerField()),
                ('p_big_tag', models.CharField(max_length=10)),
            ],
        ),
    ]
